services:
  server:
    build: .
    ports:
      - "2000:80"
    volumes:
      - /var/www/postmodernist1848.ru/database.db:/app/database.db
      - /var/www/postmodernist1848.ru/api_token:/app/api_token
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
