services:
  server:
    build: .
    ports:
      - "${POSTMODERNIST1848_RU_PORT:?}:80"
    volumes:
      - ../database.db:/app/database.db
      - ../api_token:/app/api_token
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
