name: "postmodernist1848.ru"
services:
  server:
    build: .
    ports:
      - "6969:80"
    volumes:
      - /var/www/postmodernist1848.ru/database.db:/database.db
      - /var/www/postmodernist1848.ru/api_token:/api_token
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
