package main

import (
	"log"
	"strings"
)

func migrate() {
	qs := [...][2]string{
		{"08.08.23", `\n<h6>note 1</h6>\nHello, I decided to start this thing as a convenient way to write down random thoughts.`},
		{"10.08.23", `\n<h6>note 1</h6>\n<p>\nSorry for the immediate reflective and pseudophilosophical mood right there, but I think this should all start with death. I was looking at a death certificate the other day. Imagine your death documented via the means of the state bureaurocratic machine which is the most emotionless way out there. Makes you feel that death is always there. While it obviously is, it's still quite terrifying to see the constant reminder about your loved ones. I don't think any fictional story is ever darker than that, 'cause in real life nothing ends in the end credits after an hour or so of the movie. You just learn to live it, no emotions.\n</p>\n<h6>note 2</h6>\nUmm, so let's move on to a little less depressing tone. Programming. Yes, programming. The addiction that gets you money. What an awesome occupation. Philosophically, it's very interesting, I think. Like, we, humans, in this wretched world of civilizational hubris managed to control electricity to such extent that allows us to compile human readable languages into bytes which are basically just sequences of electrons in the computer memory. And this thing runs the world now. Wow, just wow.\n<h6>note 3</h6>\nНа самом деле я использую английский как средство достижения отстраненности от того кринжа, что приходит в голову, но по большей части он все равно рождается в ней на английском, так что почему нет. Знаете, родной язык всегда более интимно воспринимается, даже не говоря о фундаментальных различиях в языках, а они есть, и на все, что вы попытаетесь выразить, будет оказано влияние языка. Про программирование мой мозг думает почти исключительно на английском. Про эмоции по большей части тоже на нем. Если же речь о чем-то новом и глубоко дорогом для меня, например о чувстве (не эмоции), это,скорее всего, будет на русском языке.`},
		{"13.08.23", `\n<h6>note 1</h6>\nHow the hell do I rest if my rest is basically recreational programming..?`},
		{"17.08.23", `\n<h6>note 1</h6>\nIt would be so awesome to try shooting real guns like they do in America. So sad I live in a postsocialist country without the rights to bear arms and be an autonomous citizen of a free state (That said, I wouldn't want to be in a country that is highly technologically advanced, highly diversified socially country, thus living with tons of idiots in the population who are controlled by CCP with TikTok).\n<h6>note 2</h6>\nThis is basically my Twitter now, lol.`},
		{"02.09.23", `\n<h6>note 1</h6>\nCan't wait until I get an access to a free hosting from Github student pack to create a nice backend for this website.`},
		{"04.10.23", `\n<h6>note 1</h6>\nОкей, ИТМО чувствуется как лучший университет в мире. Столько впечатлений у меня давно не было. Новый и большой город, а тем более такой, как Питер. Кроме этого, первый неклассический. Все это так поражает. Я уже люблю это.`},
		{"05.10.23", `\n<h6>note 1</h6>\nЯ так рад, что многие программисты на КТ осознают, что математика - это всегда плюс для разработчика. Вообще говоря, математик может всегда стать программистом. Программист, который вертит нос от изучения математики, математиком стать не сможет.`},
		{"13.10.23", `\n<h6>note 1</h6>\nParadigms in programming are all about what abstractions you choose. In procedural programming, you just use function and structs. In OOP, it's functions associated with objects (object methods). In functional languages, you choose pure functions as your primary abstraction. So it's like a spectrum between stateful and stateless, just like the political spectrum. I prefer the middle ground here and I'd love to stay with procedural programming like C. If only the world wasn't obsessed with shit like Java.`},
		{"16.10.23", `\n<h6>note 1</h6>\n<p>\nI've been thinking about God lately. So I am not christian. I wouldn't call myself christian, because I don't really believe in God. However, I like to think about transcendental stuff. I believe in tradition, so this is the only religion I could possibly be in since I am baptised since infancy and I have no access to slavic paganism.\n</p>\n<p>\nI don't like the idea of heaven. It sounds so 1984 to me (sorry for overusing 1984). So God literally takes your conscience away and makes you infinitely happy and worshipping Him. Doesn't that sound terrible? My roommate tried to persuade me otherwise by saying that you still have your will. It just doesn't contain any sin. That means that you become an ideal version of yourself. Still sound quite questionable. As for hell, there are probably many more interesting people in hell rather than in heaven (unless God is very merciful; they say He is). I hoped that in hell it's possible to interact with people like Dante Alighieri, but maybe people just go mad in hell. I just don't know. Maybe it's some sort of herecy I came up with. I am not going to lie by saying I've read bible or know christianity well...\n</p>`},
		{"24.10.23", `\n<h6>note 1</h6>\nAs your project grows, the requirements of code quality for every specific piece of code also increases, which means that you can't just slap a 100 lines of code like I did for an assignment and forget about it. You actually have to make it good and convenient to work with. Considering the additional time spent on architecturing big projects, that means time spent on a project scales nonlinearly with respect to its size.`},
		{"21.01.24", `\n<h6>note 1</h6>\nЕдинственный наркотик, который я приемлю, - это музыка. Однако не вся музыка, которая мне нравится, является наркотиком. Я предпочитаю различать удовольствие получаемое от музыки на два типа. Первый тип - телесный. Удовольствие, которые получаешь от pop или EDM, переслушивая по многу раз песни (явление \"затирания песни до дыр\", когда по 40 раз переслушиваешь одно и то же, потому что оно настолько классное), очень быстрое и скорее напоминает зависимость, нежели искусство. В противовес ему есть душевное удовольствие. Сравните какой-нибудь <a href=\"https://youtu.be/hXsdjY6PW0A?si=hTRPdhjG82yy6A6W\">романс</a> или ноктюрн Шопена с кричащей заразительной электронной вещью. Да, я не слушаю совсем попсу, поэтому это не противно, но различие нельзя не заметить. Конечно, есть и <a href=\"https://youtu.be/6fuMLjm0F4M?si=b1Dple7ctH8Yqxoo\">промежуточные случаи в EDM</a>, когда есть что-то aesthetically pleasing тоже и, наоборот, жанры типа рока, которые ближе к душевному, но и переслушивать, и получать телесное удовольствие также можно.`},
		{"26.01.24", `\n<h6>note 1</h6>\nHey, I finally got a cheap VPS and now I fully control my website. I've done tons of stuff like creating CD to deploy on push to GitHub repo or adding a chat application (please do not DDOS ME)\n<h6>note 2</h6>\nLately I've been having some sort of crisis, because they don't teach much programming in these amazing CS universities, but now, after the finals, I understand that, first of all, this is just semester 1 AND there is also going to be more useful programming later, but most importantly the theory allows me to expand my mind and push forward farther than I ever could when learning by myself, because without uni I would only be able to study programming and practical stuff. Also, I could say that I wouldn't gain these new connections and the oportunity to leave my hometown.`},
		{"19.02.24", `\n<h6>note 1</h6>\nFUUCK YEAH. КТ ИТМО ЗАДОМИНИРОВАНО. УНИЧТОЖЕНО. Ладно, там вообще не составляло труда закрыться на 4 и 5, но почему-то только единицы смогли. Не думаю, что это суперское какое-то достижение. Интересно, будем ли мы так же печься об оценках или уже пофиг, раз стипендию для первокурсников ITMO Family уже не доплачивают, а с точки зрения престижа мы уже вроде и так доказали, что можем. Также мы уже несколько месяцев рассчитываем на курс старших групп по C++, но вчера выяснилось, что не факт, что снова можно будет записаться к 38-39 на плюсы к Ивану Сорокину. Надеюсь, что набор все-таки будет, а с нашими оценками мы будем далеко не последними.`},
		{"18.03.24", `\n<h6>note 1</h6>\nНабора к Сорокину не было, ну и наплевать, если честно. Потом будет курс по выбору плюсы advanced. Скаков так Скаков. Если честно, надоело писать бесполезный учебный код типа а плюс б. Что парадигмы снова на уровне хелло ворлд, что плюсы\n<h6>note 2</h6>\nЖестко гринжу зал. Это лучшее что придумало человечество. Качалка - лекарство от депрессии, бессоницы и прочее улучшение здоровья. Я решил посушиться. Сейчас вешу 59. Еще уйдет пара килограммов и буду bulk-ить. Несмотря на калорийный дефицит, я становлюсь сильнее - перформанс в каждом упражнении повышается. Это хороший знак. Жду не дождусь, когда стану ultra lean, а потом наберу массу нормально.\nМое любимое - классика, бенч пресс. Жестко активируется грудь, очень нравится. Узким хватом на трицепс тоже приятно. Попробовал становую тягу, прикольно, надеюсь усилит lower back. С dumbbell press не разобрался, пока не особо активирует грудь. Не скипнул ни одного дня ног кста. Жалко, что в пятницу, когда мой любимый день, я часто прихожу поздно и уставший. Пробовал тренироваться, будучи уставшим. Полное неудовлетворение, никакого pump и по-моему это почти бесполезно.`},
		{"08.04.24", `\n<h6>note 1</h6>\nA lot of stuff happened since my last update. Скаков нереально скучный и лекции скорее мучение, чем веселье, как говорит Матвей. Зато пытаюсь выбить 100% на тестах по легендарной лабе по флотам, которую смог затащить только один человек за несколько лет. Это довольно весело. Новое требование по дискретке (120 задач в домашке на 4). Я не знаю уж, материал это интересный или мотивация просто появилась, но решаю теперь по 15 и более задач и получаю большое от этого огромное удовольствие. Еще пара практик и заветные 80 в кармане. \nЕсли раньше мой топ предметов выглядел примерно так:\n<ol>\n<li>Линал</li>\n<li>Матан</li>\n<li>ДМ</li>\n<li>Алгосы</li>\n<li>Прог интро</li>\n<li>ЦК</li>\n<li>ЭВМ</li>\n</ol>\n(кстати, надо будет отзыв на первый семестр как нибудь сделать)<br>\nто теперь дискретка явно на первом местe\n<h6>note 2</h6>\nЗабавное видео записал про Назара. Об этом, наверное, уже все здесь знают. Сама по себе концепция, думаю, достаточно смешная, чтобы сделать видео. Реакция на него была прикольная, в том числе от самого Назара. Немного больше людей в чате теперь, а еще кто-то читает этот кринж, который я писал когда-то только для себя. Если кто-то просит вынести в сайдбар. то я не буду этого делать, так как не хочу выставлять этот раздел напоказ. Это просто публичный дневник, который каждый может читать по своему желанию.`},
		{"04.05.24", `\n<h6>note 1</h6>\nЛаба по флотам закрылась на 15/15. Еще мне написали cease and desist за то, что я решил опубликовать перепись этого кода на плюсы. Угрожали баном. Пришлось скрыть репозиторий. <a href=\"/articles/ieee754\">Статья</a> осталась. Честно говоря, немного перегораю. Мало того, что не хочется делать ничего связанным с КТ, так еще и то, что мне нравится, не доставляет столько же удовольствия. На программирование сайд-проектов даже нет сил. Я не могу нормально тренироваться, так как мало ем и опять же нет энергии. Недавно вот просто несколько дней сидел прогал, не включая голову, безумствовао и спал часа по 4, пытаясь найти какую-то отдушину в этом всем. По итогу получился редизайн этого сайта. Мне нравится. Подробнее можно прочитать в <a href=\"/articles/history\">статье</a>. Есть еще идейки, связанные с мобильной разработкой. Самое простое уже сделал - приложение себе на телефон, чтобы редактировать эти заметки.`},
		{"05.07.24", `\n<h6>note 1</h6>\nВидимо, не стоит думать долго над тем, как матрица (КТ) не дает мне делать то, что хочется (мега стартап 78), потому что теперь я обессиленный. Я много раз говорил про определение интеллекта как способность контролировать рационально свои действия. так вот эта сверхспособность у меня пропала. Надеюсь, вернется скоро.\n<h6>note 2</h6>\nКак по мне, свобода в разы дороже денег, поэтому я бы предпочел работать над своим чем угодно, чем пойти в Яндекс. Моя мечта была бы зарабатывать кучу денег занимаясь собственным предприятием.`},
		{"15.07.24", `\n<h6>note 1</h6>\nКстати, забыл рассказать про первое собеседование Startup78. Мне кажется, вышло неплохое интервью. Задачки было нацелены на выделение навыков решения вопросов, которые возникают в реальном мире. Первый вопрос был про код на Си, где оптимизация clang давала бредовое поведение, и нужно было разобраться почему. Вторая задача состояла из рассмотрения пары сайтов, где нужно было определить фронтенд фреймворк. Далее было написание настоящего кода. Я дал интервьюируемому простой сервер на go. Нужно было создать кнопку, которая меняет значение на сервере и на клиенте (желательно без обновления страницы). Казалось бы, это просто hello world веб разработки: отправить запрос на сервер, создав api endpoint, обработать запрос, но испытуемый не справился.\n<h6>note 2</h6>\nСуки, матрица победила. Допса по линалу. Я объясню. За пару дня до экзамена нужно было сделать две домашки (30 задач). То, что все занимаются этим, ввворачивало меня наружу и в итоге я просто выпал. На экзамене мне сказали 1, 0, 0. 103 по парадигмам или пятерка по C++ не сильно меняют ситуацию. Короче, какая разница, насколько хороший ты программист, если Максим Федоров все равно 1.01x engineer, а тебя отчислят. Я очень хотел убиться.`},
		{"26.07.24", `\n<h6>note 1</h6>\nПоследнюю неделю мое расписание выглядело так: я вставал в 4, бежал на турнички, возвращался на б6, принимал холодный душ, прогал до ~9 ел куричку (50 граммов белка кста), шел в качалку, потом снова принимал ледяной душ и прогал. 10xed as a web dev. Могу сказать что у меня есть какой-то средний уровень понимания CSS, Next.js. Жду не дождусь, когда меня отчислят, так что это все будет зря.`},
		{"27.07.24", `\n<h6>note 1</h6>\nМожет быть, стоило использовать тг канал вместо этого, но моя идея в том, чтобы создать платформу. В конце концов, чат на postmodernist1848.ru не то же самое, что чат в телеграме. И это место как будто бы более секретное. У меня была идея переделать систему этих заметок и сохранять их в базе данных, но это бы сильно усложнило сервер и увеличило бы нагрузку.`},
		{"21.08.24", `\n<h6>note 1</h6>\nADDED SSR FOR THIS PAGE. Я нашел нормальную schema для сохранения заметок в базу данных, так что теперь JS только добавляет интерактив.`},
	}

	for i := range qs {
		qs[i][1] = strings.ReplaceAll(qs[i][1], "\\n", "\n")
	}

	stmt, err := database.Prepare(`DROP TABLE IF EXISTS note;`)
	if err != nil {
		log.Fatal(err)
	}
	_, err = stmt.Exec()
	if err != nil {
		log.Fatal(err)
	}
	stmt, err = database.Prepare(`create table note (
		id INTEGER PRIMARY KEY NOT NULL,
		date TEXT NOT NULL,
		html TEXT NOT NULL
	)`)
	if err != nil {
		log.Fatal(err)
	}
	_, err = stmt.Exec()
	if err != nil {
		log.Fatal(err)
	}
	stmt, err = database.Prepare("INSERT INTO note(date, html) VALUES (?, ?)")
	if err != nil {
		log.Fatal(err)
	}
	for _, q := range qs {
		_, err := stmt.Exec(q[0], q[1])
		if err != nil {
			log.Fatal(err)
		}
	}
}
