package githublines

import (
	"bytes"
	"crypto/rand"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"io"
	"io/fs"
	"log"
	"net/http"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"sync/atomic"
)

type Repo struct {
    Name string `json:"name"`
    FullName string `json:"full_name"`
}

func countLinesFile(path string) (int, error) {

    r, err := os.Open(path)
    if err != nil {
        return 0, err
    }

    buf := make([]byte, 32*1024)
    count := 0
    lineSep := []byte{'\n'}

    for {
        c, err := r.Read(buf)
        count += bytes.Count(buf[:c], lineSep)

        switch {
        case err == io.EOF:
            return count, nil

        case err != nil:
            return 0, err
        }
    }
}

func randomFilename() string {
    var randBytes = make([]byte, 16)
    rand.Read(randBytes)
    return hex.EncodeToString(randBytes)
}

type RepoData struct {
    Name string;
    LineCount int;
}

func CountLinesRepo(repo Repo, c chan RepoData) {
    url := fmt.Sprintf("https://github.com/%v", repo.FullName)
    dir := randomFilename()
    cmd := exec.Command("git", "clone", "--depth", "1", url, dir)
    out, err := cmd.CombinedOutput()
    if err != nil { 
        log.Printf("GithubLines: git clone command error: %+v", err)
        log.Printf(string(out))
        c <- RepoData { repo.Name + " (error)", 0 }
        return
    }

    var linesCount int

    err = filepath.WalkDir(dir, func(path string, d fs.DirEntry, err error) error {
        if strings.HasSuffix(path, "/.git") {
            return filepath.SkipDir
        }
        if (!d.IsDir()) {
            ext := filepath.Ext(path)
            _, matchedFile := codeFilenames[d.Name()];
            _, matchedExt := codeFiletypes[ext]
            if matchedFile || matchedExt {
                count, err := countLinesFile(path)
                if err != nil {
                    log.Printf("countLinesFile error: %+v", err)
                    return err
                }
                linesCount += count
            }
        }
        return nil
    })
    if err != nil {
        log.Printf("Walkdir error: %+v", err)
        c <- RepoData { repo.Name + " (error)", 0 }
        return
    }
    os.RemoveAll(dir)
    c <- RepoData { repo.Name, linesCount }

}

const countlines_requests_limit = 5
var countlines_current_requests atomic.Int32

func ServeCountlines(w http.ResponseWriter, r *http.Request) {

    if countlines_current_requests.Load() >= countlines_requests_limit {
        io.WriteString(w, "Too many requests are being processed currently. Try later")
        return
    }
    countlines_current_requests.Add(1)
    defer countlines_current_requests.Add(-1)

	username := strings.TrimPrefix(r.URL.Path, "/countlines/")
	log.Printf("Handling countlines/ request. Username: %v", username)
	url := fmt.Sprintf("https://api.github.com/users/%v/repos", username)
	resp, err := http.Get(url)
	if err != nil {
		log.Println("GithubLines: HTTP GET error for", username, err)
		io.WriteString(w, "Failure getting data from Github")
		return
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		bodyBytes, err := io.ReadAll(resp.Body)
		if err != nil {
			log.Println("GithubLines: HTTP resp not OK for", username, resp.StatusCode)
		} else {
			log.Println("GithubLines: HTTP resp not OK for", username, string(bodyBytes))
		}
		io.WriteString(w, "Failure getting data from Github")
		return
	}
	var result []Repo
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
		log.Println("GithubLines: Decoding error for", username, err)
		io.WriteString(w, "Failure decoding data from Github")
		return
	}
	c := make(chan RepoData)
	for _, repo := range result {
		go CountLinesRepo(repo, c)
	}
	io.WriteString(w, "<ul>")
	totalCount := 0
	for range result {
		repo := <-c
		fmt.Fprintf(w, "<li>%v: %v lines</li>", repo.Name, repo.LineCount)
		totalCount += repo.LineCount
	}
	io.WriteString(w, "<ul>")
	fmt.Fprintf(w, "Total: %v lines", totalCount)

}


type void struct{}

// got the list from https://github.com/AlDanial/cloc
var codeFiletypes = map[string]void {
    ".abap"        : {},
    ".ac"          : {},
    ".ada"         : {},
    ".adb"         : {},
    ".ads"         : {},
    ".adso"        : {},
    ".ahkl"        : {},
    ".ahk"         : {},
    ".agda"        : {},
    ".lagda"       : {},
    ".aj"          : {},
    ".am"          : {},
    ".ample"       : {},
    ".apl"         : {},
    ".apla"        : {},
    ".aplf"        : {},
    ".aplo"        : {},
    ".apln"        : {},
    ".aplc"        : {},
    ".apli"        : {},
    ".dyalog"      : {},
    ".dyapp"       : {},
    ".mipage"      : {},
    ".as"          : {},
    ".adoc"        : {},
    ".asciidoc"    : {},
    ".dofile"      : {},
    ".startup"     : {},
    ".axd"         : {},
    ".ashx"        : {},
    ".asa"         : {},
    ".asax"        : {},
    ".ascx"        : {},
    ".asd"         : {}, 
    ".nasm"        : {},
    ".a51"         : {},
    ".asm"         : {},
    ".asmx"        : {},
    ".asp"         : {},
    ".aspx"        : {},
    ".master"      : {},
    ".sitemap"     : {},
    ".asy"         : {},
    ".cshtml"      : {},
    ".razor"       : {},
    ".nawk"        : {},
    ".mawk"        : {},
    ".gawk"        : {},
    ".auk"         : {},
    ".awk"         : {},
    ".bash"        : {},
    ".bazel"       : {},
    ".BUILD"       : {},
    ".dxl"         : {},
    ".bat"         : {},
    ".BAT"         : {},
    ".cmd"         : {},
    ".CMD"         : {},
    ".btm"         : {},
    ".BTM"         : {},
    ".blade"       : {},
    ".blade.php"   : {},
    ".build.xml"   : {},
    ".b"           : {},
    ".bf"          : {},
    ".brs"         : {},
    ".bzl"         : {},
    ".btp"         : {},
    ".odx"         : {},
    ".carbon"      : {},
    ".cpy"         : {},
    ".cobol"       : {},
    ".ccp"         : {},
    ".cbl"         : {},
    ".CBL"         : {},
    ".idc"         : {},
    ".cats"        : {},
    ".c"           : {},
    ".c++"         : {},
    ".C"           : {},
    ".cc"          : {},
    ".ccm"         : {},
    ".c++m"        : {},
    ".cppm"        : {},
    ".cxxm"        : {},
    ".h++"         : {},
    ".inl"         : {},
    ".ipp"         : {},
    ".ixx"         : {},
    ".tcc"         : {},
    ".tpp"         : {},
    ".ccs"         : {},
    ".cfc"         : {},
    ".cfml"        : {},
    ".cfm"         : {},
    ".chpl"        : {},
    ".cl"          : {},
    ".hic"         : {},
    ".cljx"        : {},
    ".cljscm"      : {},
    ".cljs.hl"     : {},
    ".cl2"         : {},
    ".boot"        : {},
    ".clj"         : {},
    ".cljs"        : {},
    ".cljc"        : {},
    ".cls"         : {},
    ".cmake"       : {},
    ".cob"         : {},
    ".COB"         : {},
    ".cocoa5"      : {},
    ".c5"          : {},
    ".cpkg5"       : {},
    ".cocoa5server": {},
    ".iced"        : {},
    ".cjsx"        : {},
    ".cakefile"    : {},
    "._coffee"     : {},
    ".coffee"      : {},
    ".component"   : {},
    ".cg3"         : {},
    ".rlx"         : {},
    ".Containerfile"  : {},
    ".cpp"         : {},
    ".CPP"         : {},
    ".cr"          : {},
    ".cs"          : {},
    ".designer.cs" : {},
    ".cake"        : {},
    ".csh"         : {},
    ".cson"        : {},
    ".css"         : {},
    ".csv"         : {},
    ".cu"          : {},
    ".cuh"         : {},
    ".cxx"         : {},
    ".d"           : {},
    ".da"          : {},
    ".dart"        : {},
    ".dsc"         : {},
    ".derw"        : {},
    ".def"         : {},
    ".dhall"       : {},
    ".dt"          : {},
    ".patch"       : {},
    ".diff"        : {},
    ".dmap"        : {},
    ".sthlp"       : {},
    ".matah"       : {},
    ".mata"        : {},
    ".ihlp"        : {},
    ".doh"         : {},
    ".ado"         : {},
    ".do"          : {},
    ".DO"          : {},
    ".Dockerfile"  : {},
    ".dockerfile"  : {},
    ".pascal"      : {},
    ".lpr"         : {},
    ".dfm"         : {},
    ".dpr"         : {},
    ".dita"        : {},
    ".drl"         : {},
    ".dtd"         : {},
    ".ec"          : {},
    ".ecpp"        : {},
    ".eex"         : {},
    ".el"          : {},
    ".elm"         : {},
    ".exs"         : {},
    ".ex"          : {},
    ".ecr"         : {},
    ".ejs"         : {},
    ".erb"         : {},
    ".ERB"         : {},
    ".yrl"         : {},
    ".xrl"         : {},
    ".rebar.lock"  : {},
    ".rebar.config.lock": {},
    ".rebar.config": {},
    ".emakefile"   : {},
    ".app.src"     : {},
    ".erl"         : {},
    ".exp"         : {},
    ".4th"         : {},
    ".fish"        : {},
    ".fsl"         : {},
    ".jssm"        : {},
    ".fnl"         : {},
    ".forth"       : {},
    ".fr"          : {},
    ".frt"         : {},
    ".fth"         : {},
    ".f83"         : {},
    ".fb"          : {},
    ".fpm"         : {},
    ".e4"          : {},
    ".rx"          : {},
    ".ft"          : {},
    ".f77"         : {},
    ".F77"         : {},
    ".f90"         : {},
    ".F90"         : {},
    ".f95"         : {},
    ".F95"         : {},
    ".f"           : {},
    ".F"           : {},
    ".for"         : {},
    ".FOR"         : {},
    ".ftl"         : {},
    ".ftn"         : {},
    ".FTN"         : {},
    ".fmt"         : {},
    ".focexec"     : {},
    ".fs"          : {},
    ".fsi"         : {},
    ".fsx"         : {},
    ".fut"         : {},
    ".fxml"        : {},
    ".gnumakefile" : {},
    ".Gnumakefile" : {},
    ".gd"          : {},
    ".gdshader"    : {},
    ".vshader"     : {},
    ".vsh"         : {},
    ".vrx"         : {},
    ".gshader"     : {},
    ".glslv"       : {},
    ".geo"         : {},
    ".fshader"     : {},
    ".fsh"         : {},
    ".frg"         : {},
    ".fp"          : {},
    ".fbs"         : {},
    ".glsl"        : {},
    ".graphqls"    : {},
    ".gql"         : {},
    ".graphql"     : {},
    ".vert"        : {},
    ".tesc"        : {},
    ".tese"        : {},
    ".geom"        : {},
    ".feature"     : {},
    ".frag"        : {},
    ".comp"        : {},
    ".g"           : {},
    ".g4"          : {},
    ".gleam"       : {},
    ".go"          : {},
    ".gsp"         : {},
    ".jenkinsfile" : {},
    ".gvy"         : {},
    ".gtpl"        : {},
    ".grt"         : {},
    ".groovy"      : {},
    ".gant"        : {},
    ".gradle"      : {},
    ".gradle.kts"  : {},
    ".h"           : {},
    ".H"           : {},
    ".hh"          : {},
    ".hpp"         : {},
    ".hxx"         : {},
    ".hb"          : {},
    ".hrl"         : {},
    ".hsc"         : {},
    ".hs"          : {},
    ".tfvars"      : {},
    ".hcl"         : {},
    ".tf"          : {},
    ".nomad"       : {},
    ".hlsli"       : {},
    ".fxh"         : {},
    ".hlsl"        : {},
    ".shader"      : {},
    ".cg"          : {},
    ".cginc"       : {},
    ".haml.deface" : {},
    ".haml"        : {},
    ".handlebars"  : {},
    ".hbs"         : {},
    ".ha"          : {},
    ".hxsl"        : {},
    ".hx"          : {},
    ".HC"          : {},
    ".hoon"        : {},
    ".xht"         : {},
    ".html.hl"     : {},
    ".htm"         : {},
    ".html"        : {},
    ".heex"        : {},
    ".i3"          : {},
    ".ice"         : {},
    ".icl"         : {},
    ".dcl"         : {},
    ".dlm"         : {},
    ".idl"         : {},
    ".idr"         : {},
    ".lidr"        : {},
    ".imba"        : {},
    ".prefs"       : {},
    ".lektorproject": {},
    ".buildozer.spec": {},
    ".ini"         : {},
    ".editorconfig": {},
    ".ism"         : {},
    ".ipl"         : {},
    ".pro"         : {},
    ".ig"          : {},
    ".il"          : {},
    ".ils"         : {},
    ".inc"         : {},
    ".ino"         : {},
    ".ipf"         : {},
    ".pde"         : {},
    ".itk"         : {},
    ".java"        : {},
    ".jcl"         : {},
    ".jl"          : {},
    ".jai"         : {},
    ".xsjslib"     : {},
    ".xsjs"        : {},
    ".ssjs"        : {},
    ".sjs"         : {},
    ".pac"         : {},
    ".njs"         : {},
    ".mjs"         : {},
    ".cjs"         : {},
    ".jss"         : {},
    ".jsm"         : {},
    ".jsfl"        : {},
    ".jscad"       : {},
    ".jsb"         : {},
    ".jakefile"    : {},
    ".jake"        : {},
    ".bones"       : {},
    "._js"         : {},
    ".js"          : {},
    ".es6"         : {},
    ".jsf"         : {},
    ".jsx"         : {},
    ".xhtml"       : {},
    ".jinja"       : {},
    ".jinja2"      : {},
    ".yyp"         : {},
    ".webmanifest" : {},
    ".webapp"      : {},
    ".topojson"    : {},
    ".tfstate.backup": {},
    ".tfstate"     : {},
    ".mcmod.info"  : {},
    ".mcmeta"      : {},
    ".json-tmlanguage": {},
    ".jsonl"       : {},
    ".har"         : {},
    ".gltf"        : {},
    ".geojson"     : {},
    ".composer.lock": {},
    ".avsc"        : {},
    ".watchmanconfig": {},
    ".tern-project": {},
    ".tern-config" : {},
    ".htmlhintrc"  : {},
    ".arcconfig"   : {},
    ".json"        : {},
    ".json5"       : {},
    ".jsp"         : {},
    ".jspf"        : {},
    ".junos"       : {},
    ".vm"          : {},
    ".kv"          : {},
    ".ksc"         : {},
    ".ksh"         : {},
    ".ktm"         : {},
    ".kt"          : {},
    ".kts"         : {},
    ".hlean"       : {},
    ".lean"        : {},
    ".lhs"         : {},
    ".lex"         : {},
    ".l"           : {},
    ".ld"          : {},
    ".lem"         : {},
    ".less"        : {},
    ".lfe"         : {},
    ".liquid"      : {},
    ".lsp"         : {},
    ".lisp"        : {},
    ".ll"          : {},
    ".lgt"         : {},
    ".logtalk"     : {},
    ".wlua"        : {},
    ".rbxs"        : {},
    ".pd_lua"      : {},
    ".p8"          : {},
    ".nse"         : {},
    ".lua"         : {},
    ".m3"          : {},
    ".m4"          : {},
    ".makefile"    : {},
    ".Makefile"    : {},
    ".mao"         : {},
    ".mako"        : {},
    ".workbook"    : {},
    ".ronn"        : {},
    ".mkdown"      : {},
    ".mkdn"        : {},
    ".mkd"         : {},
    ".mdx"         : {},
    ".mdwn"        : {},
    ".mdown"       : {},
    ".markdown"    : {},
    ".contents.lr" : {},
    ".md"          : {},
    ".mc"          : {},
    ".met"         : {},
    ".mg"          : {},
    ".mojom"       : {},
    ".meson.build" : {},
    ".metal"       : {},
    ".mk"          : {},
    ".ml4"         : {},
    ".eliomi"      : {},
    ".eliom"       : {},
    ".ml"          : {},
    ".mli"         : {},
    ".mly"         : {},
    ".mll"         : {},
    ".m"           : {},
    ".mm"          : {},
    ".msg"         : {},
    ".nbp"         : {},
    ".mathematica" : {},
    ".ma"          : {},
    ".cdf"         : {},
    ".mt"          : {},
    ".wl"          : {},
    ".wlt"         : {},
    ".mustache"    : {},
    ".wdproj"      : {},
    ".csproj"      : {},
    ".vcproj"      : {},
    ".wixproj"     : {},
    ".btproj"      : {},
    ".msbuild"     : {},
    ".sln"         : {},
    ".mps"         : {},
    ".mth"         : {},
    ".n"           : {},
    ".nlogo"       : {},
    ".nls"         : {},
    ".nims"        : {},
    ".nimrod"      : {},
    ".nimble"      : {},
    ".nim.cfg"     : {},
    ".nim"         : {},
    ".nix"         : {},
    ".nut"         : {},
    ".njk"         : {},
    ".odin"        : {},
    ".oscript"     : {},
    ".bod"         : {},
    ".spc"         : {},
    ".fnc"         : {},
    ".prc"         : {},
    ".trg"         : {},
    ".pad"         : {},
    ".page"        : {},
    ".pas"         : {},
    ".pcc"         : {},
    ".rexfile"     : {},
    ".psgi"        : {},
    ".ph"          : {},
    ".makefile.pl" : {},
    ".cpanfile"    : {},
    ".al"          : {},
    ".ack"         : {},
    ".perl"        : {},
    ".pfo"         : {},
    ".pgc"         : {},
    ".phpt"        : {},
    ".phps"        : {},
    ".phakefile"   : {},
    ".ctp"         : {},
    ".aw"          : {},
    ".php_cs.dist" : {},
    ".php_cs"      : {},
    ".php3"        : {},
    ".php4"        : {},
    ".php5"        : {},
    ".php"         : {},
    ".phtml"       : {},
    ".pig"         : {},
    ".plh"         : {},
    ".pl"          : {},
    ".PL"          : {},
    ".p6"          : {},
    ".P6"          : {},
    ".plx"         : {},
    ".pm"          : {},
    ".pm6"         : {},
    ".raku"        : {},
    ".rakumod"     : {},
    ".pom.xml"     : {},
    ".pom"         : {},
    ".scad"        : {},
    ".yap"         : {},
    ".prolog"      : {},
    ".P"           : {},
    ".p"           : {},
    ".pp"          : {},
    ".viw"         : {},
    ".udf"         : {},
    ".tab"         : {},
    ".mysql"       : {},
    ".cql"         : {},
    ".psql"        : {},
    ".xpy"         : {},
    ".wsgi"        : {},
    ".wscript"     : {},
    ".workspace"   : {},
    ".tac"         : {},
    ".snakefile"   : {},
    ".sconstruct"  : {},
    ".sconscript"  : {},
    ".pyt"         : {},
    ".pyp"         : {},
    ".pyi"         : {},
    ".pyde"        : {},
    ".py3"         : {},
    ".lmi"         : {},
    ".gypi"        : {},
    ".gyp"         : {},
    ".build.bazel" : {},
    ".buck"        : {},
    ".gclient"     : {},
    ".py"          : {},
    ".pyw"         : {},
    ".ipynb"       : {},
    ".pyj"         : {},
    ".pxi"         : {},
    ".pxd"         : {},
    ".pyx"         : {},
    ".qbs"         : {},
    ".qml"         : {},
    ".watchr"      : {},
    ".vagrantfile" : {},
    ".thorfile"    : {},
    ".thor"        : {},
    ".snapfile"    : {},
    ".ru"          : {},
    ".rbx"         : {},
    ".rbw"         : {},
    ".rbuild"      : {},
    ".rabl"        : {},
    ".puppetfile"  : {},
    ".podfile"     : {},
    ".mspec"       : {},
    ".mavenfile"   : {},
    ".jbuilder"    : {},
    ".jarfile"     : {},
    ".guardfile"   : {},
    ".god"         : {},
    ".gemspec"     : {},
    ".gemfile.lock": {},
    ".gemfile"     : {},
    ".fastfile"    : {},
    ".eye"         : {},
    ".deliverfile" : {},
    ".dangerfile"  : {},
    ".capfile"     : {},
    ".buildfile"   : {},
    ".builder"     : {},
    ".brewfile"    : {},
    ".berksfile"   : {},
    ".appraisals"  : {},
    ".pryrc"       : {},
    ".irbrc"       : {},
    ".rb"          : {},
    ".podspec"     : {},
    ".rake"        : {},
    ".rex"         : {},
    ".pprx"        : {},
    ".rexx"        : {},
    ".rhtml"       : {},
    ".circom"      : {},
    ".cairo"       : {},
    ".rs.in"       : {},
    ".rs"          : {},
    ".rst.txt"     : {},
    ".rest.txt"    : {},
    ".rest"        : {},
    ".rst"         : {},
    ".s"           : {},
    ".S"           : {},
    ".SCA"         : {},
    ".sca"         : {},
    ".sbt"         : {},
    ".kojo"        : {},
    ".scala"       : {},
    ".sbl"         : {},
    ".SBL"         : {},
    ".sed"         : {},
    ".sp"          : {},
    ".sol"         : {},
    ".p4"          : {},
    ".ses"         : {},
    ".pcl"         : {},
    ".peg"         : {},
    ".pegjs"       : {},
    ".peggy"       : {},
    ".pest"        : {},
    ".tspeg"       : {},
    ".jspeg"       : {},
    ".pl1"         : {},
    ".plm"         : {},
    ".lit"         : {},
    ".puml"        : {},
    ".properties"  : {},
    ".po"          : {},
    ".pony"        : {},
    ".pbt"         : {},
    ".sra"         : {},
    ".srf"         : {},
    ".srm"         : {},
    ".srs"         : {},
    ".sru"         : {},
    ".srw"         : {},
    ".jade"        : {},
    ".pug"         : {},
    ".purs"        : {},
    ".prefab"      : {},
    ".proto"       : {},
    ".mat"         : {},
    ".ps1"         : {},
    ".psd1"        : {},
    ".psm1"        : {},
    ".rsx"         : {},
    ".rd"          : {},
    ".expr-dist"   : {},
    ".rprofile"    : {},
    ".R"           : {},
    ".r"           : {},
    ".raml"        : {},
    ".ring"        : {},
    ".rh"          : {},
    ".rform"       : {},
    ".rktd"        : {},
    ".rkt"         : {},
    ".rktl"        : {},
    ".Rmd"         : {},
    ".re"          : {},
    ".rei"         : {},
    ".res"         : {},
    ".resi"        : {},
    ".scrbl"       : {},
    ".sps"         : {},
    ".sc"          : {},
    ".ss"          : {},
    ".scm"         : {},
    ".sch"         : {},
    ".sls"         : {},
    ".sld"         : {},
    ".robot"       : {},
    ".rc"          : {},
    ".rc2"         : {},
    ".sas"         : {},
    ".sass"        : {},
    ".scss"        : {},
    ".sh"          : {},
    ".smarty"      : {},
    ".sml"         : {},
    ".sig"         : {},
    ".fun"         : {},
    ".slim"        : {},
    ".e"           : {},
    ".sql"         : {},
    ".SQL"         : {},
    ".sss"         : {},
    ".st"          : {},
    ".styl"        : {},
    ".i"           : {},
    ".svelte"      : {},
    ".sv"          : {},
    ".svh"         : {},
    ".svg"         : {},
    ".SVG"         : {},
    ".v"           : {},
    ".td"          : {},
    ".tcl"         : {},
    ".tcsh"        : {},
    ".tk"          : {},
    ".teal"        : {},
    ".mkvi"        : {},
    ".mkiv"        : {},
    ".mkii"        : {},
    ".ltx"         : {},
    ".lbx"         : {},
    ".ins"         : {},
    ".cbx"         : {},
    ".bib"         : {},
    ".bbx"         : {},
    ".aux"         : {},
    ".tex"         : {}, 
    ".toml"        : {},
    ".sty"         : {},
    ".dtx"         : {},
    ".bst"         : {},
    ".txt"         : {},
    ".text"        : {},
    ".tres"        : {},
    ".tscn"        : {},
    ".thrift"      : {},
    ".tpl"         : {},
    ".trigger"     : {},
    ".ttcn"        : {},
    ".ttcn2"       : {},
    ".ttcn3"       : {},
    ".ttcnpp"      : {},
    ".sdl"         : {},
    ".ssc"         : {},
    ".sdt"         : {},
    ".spd"         : {},
    ".sst"         : {},
    ".rou"         : {},
    ".cin"         : {},
    ".cii"         : {},
    ".interface"   : {},
    ".in1"         : {},
    ".in2"         : {},
    ".in3"         : {},
    ".in4"         : {},
    ".inf"         : {},
    ".tpd"         : {},
    ".ts"          : {},
    ".tsx"         : {},
    ".tss"         : {},
    ".twig"        : {},
    ".typ"         : {},
    ".um"          : {},
    ".ui"          : {},
    ".glade"       : {},
    ".vala"        : {},
    ".vapi"        : {},
    ".vhw"         : {},
    ".vht"         : {},
    ".vhs"         : {},
    ".vho"         : {},
    ".vhi"         : {},
    ".vhf"         : {},
    ".vhd"         : {},
    ".VHD"         : {},
    ".vhdl"        : {},
    ".VHDL"        : {},
    ".bas"         : {},
    ".BAS"         : {},
    ".ctl"         : {},
    ".dsr"         : {},
    ".frm"         : {},
    ".frx"         : {},
    ".FRX"         : {},
    ".vba"         : {},
    ".VBA"         : {},
    ".vbhtml"      : {},
    ".VBHTML"      : {},
    ".vbproj"      : {},
    ".vbp"         : {},
    ".vbs"         : {},
    ".VBS"         : {},
    ".vb"          : {},
    ".VB"          : {},
    ".vbw"         : {},
    ".vue"         : {},
    ".webinfo"     : {},
    ".wsdl"        : {},
    ".x"           : {},
    ".xm"          : {},
    ".xpo"         : {},
    ".xmi"         : {},
    ".XMI"         : {},
    ".zcml"        : {},
    ".xul"         : {},
    ".xspec"       : {},
    ".xproj"       : {},
    ".xml.dist"    : {},
    ".xliff"       : {},
    ".xlf"         : {},
    ".xib"         : {},
    ".xacro"       : {},
    ".x3d"         : {},
    ".wsf"         : {},
    ".web.release.config": {},
    ".web.debug.config": {},
    ".web.config"  : {},
    ".wxml"        : {},
    ".wxss"        : {},
    ".vxml"        : {},
    ".vstemplate"  : {},
    ".vssettings"  : {},
    ".vsixmanifest": {},
    ".vcxproj"     : {},
    ".ux"          : {},
    ".urdf"        : {},
    ".tmtheme"     : {},
    ".tmsnippet"   : {},
    ".tmpreferences": {},
    ".tmlanguage"  : {},
    ".tml"         : {},
    ".tmcommand"   : {},
    ".targets"     : {},
    ".sublime-snippet": {},
    ".sttheme"     : {},
    ".storyboard"  : {},
    ".srdf"        : {},
    ".shproj"      : {},
    ".sfproj"      : {},
    ".settings.stylecop": {},
    ".scxml"       : {},
    ".rss"         : {},
    ".resx"        : {},
    ".rdf"         : {},
    ".pt"          : {},
    ".psc1"        : {},
    ".ps1xml"      : {},
    ".props"       : {},
    ".proj"        : {},
    ".plist"       : {},
    ".pkgproj"     : {},
    ".packages.config": {},
    ".osm"         : {},
    ".odd"         : {},
    ".nuspec"      : {},
    ".nuget.config": {},
    ".nproj"       : {},
    ".ndproj"      : {},
    ".natvis"      : {},
    ".mjml"        : {},
    ".mdpolicy"    : {},
    ".launch"      : {},
    ".kml"         : {},
    ".jsproj"      : {},
    ".jelly"       : {},
    ".ivy"         : {},
    ".iml"         : {},
    ".grxml"       : {},
    ".gmx"         : {},
    ".fsproj"      : {},
    ".filters"     : {},
    ".dotsettings" : {},
    ".dll.config"  : {},
    ".ditaval"     : {},
    ".ditamap"     : {},
    ".depproj"     : {},
    ".ct"          : {},
    ".csl"         : {},
    ".csdef"       : {},
    ".cscfg"       : {},
    ".cproject"    : {},
    ".clixml"      : {},
    ".ccxml"       : {},
    ".ccproj"      : {},
    ".builds"      : {},
    ".axml"        : {},
    ".app.config"  : {},
    ".ant"         : {},
    ".admx"        : {},
    ".adml"        : {},
    ".project"     : {},
    ".classpath"   : {},
    ".xml"         : {},
    ".XML"         : {},
    ".mxml"        : {},
    ".xml.builder" : {},
    ".build"       : {},
    ".vim"         : {},
    ".swift"       : {},
    ".xaml"        : {},
    ".wast"        : {},
    ".wat"         : {},
    ".wgsl"        : {},
    ".wxs"         : {},
    ".wxi"         : {},
    ".wxl"         : {},
    ".prw"         : {},
    ".prg"         : {},
    ".ch"          : {},
    ".xqy"         : {},
    ".xqm"         : {},
    ".xql"         : {},
    ".xq"          : {},
    ".xquery"      : {},
    ".xsd"         : {},
    ".XSD"         : {},
    ".xslt"        : {},
    ".XSLT"        : {},
    ".xsl"         : {},
    ".XSL"         : {},
    ".xtend"       : {},
    ".yacc"        : {},
    ".y"           : {},
    ".yml.mysql"   : {},
    ".yaml-tmlanguage": {},
    ".syntax"      : {},
    ".sublime-syntax": {},
    ".rviz"        : {},
    ".reek"        : {},
    ".mir"         : {},
    ".glide.lock"  : {},
    ".gemrc"       : {},
    ".clang-tidy"  : {},
    ".clang-format": {},
    ".yaml"        : {},
    ".yml"         : {},
    ".zig"         : {},
    ".zsh"         : {},
}
var codeFilenames  = map[string]void {
    "build.xml"         : {},
    "BUILD"             : {},
    "WORKSPACE"         : {},
    "cmakelists.txt"    : {},
    "CMakeLists.txt"    : {},
    "Jamfile"           : {},
    "jamfile"           : {},
    "Jamrules"          : {},
    "Makefile"          : {},
    "makefile"          : {},
    "meson.build"       : {},
    "Gnumakefile"       : {},
    "gnumakefile"       : {},
    "pom.xml"           : {},
    "Rakefile"          : {},
    "rakefile"          : {},
    "Dockerfile"        : {},
    "Dockerfile.m4"     : {},
    "Dockerfile.cmake"  : {},
    "dockerfile"        : {},
    "dockerfile.m4"     : {},
    "dockerfile.cmake"  : {},
    "Containerfile"     : {},
}
