name: postmodernist1848.ru CD
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      env:
        SERVER_KEY: ${{ secrets.SERVER_KEY }}
        SERVER_CRT: ${{ secrets.SERVER_CRT }}
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        envs: SERVER_KEY, SERVER_CRT,
        script: |
          cd /var/www/postmodernist1848.ru/deployment/
          git fetch origin master
          git reset --hard origin/master
          docker compose up --build -d
  Test:
    needs:
      build
    runs-on: ubuntu-latest
    steps:
    - name: Attempt to curl postmodernist1848.ru
      run: |
        echo "# Curl https://postmodernist1848.ru" >> $GITHUB_STEP_SUMMARY
        echo '```html' >> $GITHUB_STEP_SUMMARY
        curl https://postmodernist1848.ru >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY

