name: postmodernist1848.ru CD
on:
  push:
    branches: [ master ]

jobs:
  Build:
    runs-on: ubuntu-latest
    environment: production
    steps:
    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        envs: SERVER_KEY, SERVER_CRT,
        script: /var/www/deploy postmodernist1848_ru --build
  Test:
    needs:
      Build
    runs-on: ubuntu-latest
    steps:
    - name: Attempt to curl postmodernist1848.ru
      run: |
        echo "# Curl https://postmodernist1848.ru" >> $GITHUB_STEP_SUMMARY
        echo '```html' >> $GITHUB_STEP_SUMMARY
        curl https://postmodernist1848.ru >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY

