name: postmodernist1848.ru CD
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        script: |
          if cd ~/postmodernist1848.ru; then
            git pull
          else
            git clone git@github.com:postmodernist1848/postmodernist1848.ru && cd ~/postmodernist1848.ru
          fi
          ./deploy.sh

